version: '3.8'
networks:
  shared-network:
services:
  nginx:
    image: nginx:1.27.2-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fasting-be
      - fasting-ui
    networks:
      - shared-network

  fasting-be:
    build: .././fasting-be
    container_name: fasting-be
    ports:
      - "5000:3000"
    networks:
      - shared-network

  frontend:
    build: .././frontend
    container_name: frontend
    ports:
      - "5001:80"
      - "5002:443"
    networks:
      - shared-network