version: "3.8"

networks:
  shared-network:

services:
  nginx:
    image: nginx:1.27.2-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fasting-be
      - fasting-ui
    networks:
      - shared-network

  fasting-be:
    build: .././fasting-be
    container_name: fasting-be
    ports:
      - "5000:3000"
    depends_on:
      - postgres # Ensures the DB is ready before starting BE
    environment:
      POSTGRES_USER: fasting_user
      POSTGRES_PASSWORD: fasting_pass
      POSTGRES_DB: fasting_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    networks:
      - shared-network

  fasting-ui:
    build: .././fasting-ui
    container_name: fasting-ui
    ports:
      - "5001:80"
      - "5002:443"
    networks:
      - shared-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fasting_user
      POSTGRES_PASSWORD: fasting_pass
      POSTGRES_DB: fasting_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network

volumes:
  postgres-data:
